// frontend/react-rules-practice/src/features/incidents/pages/IncidentDashboardPage.tsx
import { useCallback, useMemo, useState } from 'react'
import { IncidentFilters } from '../components/IncidentFilters'
import { IncidentList } from '../components/IncidentList'
import { IncidentStats } from '../components/IncidentStats'
import { useIncidents } from '../hooks/useIncidents'
import type { Incident, IncidentSeverity, IncidentStatus } from '../types/incidentTypes'
import { Loading } from '../../../shared/components/Loading'
import type { SeverityFilter, StatusFilter } from '../components/IncidentFilters'
import './IncidentDashboardPage.css'

type StatFilter =
  | { type: 'ALL' }
  | { type: 'STATUS'; value: IncidentStatus }
  | { type: 'SEVERITY'; value: IncidentSeverity }

/**
* Keeps filtering logic outside the component body to make it easy to test,
* read and reuse. The dashboard owns the filter state and derives the visible
* incidents from the full incident list.
*/
function filterIncidents(
  incidents: Incident[],
  selectedStatus: StatusFilter,
  selectedSeverity: SeverityFilter,
): Incident[] {
  return incidents.filter((incident) => {
    const matchesStatus = selectedStatus === 'ALL' || incident.status === selectedStatus
    const matchesSeverity = selectedSeverity === 'ALL' || incident.severity === selectedSeverity

    return matchesStatus && matchesSeverity
  })
}

export function IncidentDashboardPage() {
  const { incidents, stats, loading, error, reload } = useIncidents()

  const [selectedStatus, setSelectedStatus] = useState<StatusFilter>('ALL')
  const [selectedSeverity, setSelectedSeverity] = useState<SeverityFilter>('ALL')

  /**
 * Statistic cards act as shortcuts for dashboard filters.
 * Clicking a status resets the severity filter, and clicking a severity resets
 * the status filter, so the resulting view stays explicit and predictable.
 */
  const handleStatClick = useCallback((filter: StatFilter) => {
    if (filter.type === 'ALL') {
      setSelectedStatus('ALL')
      setSelectedSeverity('ALL')
      return
    }

    if (filter.type === 'STATUS') {
      setSelectedStatus(filter.value)
      setSelectedSeverity('ALL')
      return
    }

    setSelectedSeverity(filter.value)
    setSelectedStatus('ALL')
  }, [])

  const filteredIncidents = useMemo(
    () => filterIncidents(incidents, selectedStatus, selectedSeverity),
    [incidents, selectedStatus, selectedSeverity],
  )

  if (loading) {
    return <Loading />
  }

  if (error) {
    return (
      <section className="dashboard-error" role="alert">
        <h2>Unable to load incidents</h2>
        <p>{error}</p>
        <button type="button" onClick={() => void reload()}>
          Retry
        </button>
      </section>
    )
  }

  return (
    <main className="dashboard-page">
      <header className="dashboard-header">
        <h1 className="dashboard-title">War Room Incident Dashboard</h1>
        <p className="dashboard-subtitle">
          Diagnose, investigate and resolve technical incidents.
        </p>
      </header>

      <div className="dashboard-content">
        <IncidentStats stats={stats} onStatClick={handleStatClick} />

        <IncidentFilters
          selectedStatus={selectedStatus}
          selectedSeverity={selectedSeverity}
          onStatusChange={setSelectedStatus}
          onSeverityChange={setSelectedSeverity}
        />

        <p className="dashboard-count">
          Showing {filteredIncidents.length} of {incidents.length} incidents.
        </p>

        <IncidentList incidents={filteredIncidents} />
      </div>
    </main>
  )
}

// frontend/angular-rules-practice/src/app/features/incidents/pages/incident-dashboard-page/incident-dashboard-page.component.ts
import { AsyncPipe } from '@angular/common'
import { Component, inject, signal } from '@angular/core'
import { combineLatest, map } from 'rxjs'
import { IncidentService } from '../../data-access/incident.service'
import type {
  SeverityFilter,
  StatFilter,
  StatusFilter,
} from '../../models/incident-filter.model'
import { IncidentFiltersComponent } from '../../ui/incident-filters/incident-filters.component'
import { IncidentListComponent } from '../../ui/incident-list/incident-list.component'
import { IncidentStatsComponent } from '../../ui/incident-stats/incident-stats.component'
import { filterIncidents } from '../../utils/incident-filters.util'

@Component({
  selector: 'app-incident-dashboard-page',
  imports: [AsyncPipe, IncidentStatsComponent, IncidentFiltersComponent, IncidentListComponent],
  templateUrl: './incident-dashboard-page.component.html',
  styleUrl: './incident-dashboard-page.component.css',
})
export class IncidentDashboardPageComponent {
  private readonly incidentService = inject(IncidentService)

  readonly selectedStatus = signal<StatusFilter>('ALL')
  readonly selectedSeverity = signal<SeverityFilter>('ALL')

  readonly incidents$ = this.incidentService.findAll()
  readonly stats$ = this.incidentService.getStats()

  readonly vm$ = combineLatest({
    incidents: this.incidents$,
    stats: this.stats$,
  }).pipe(
    map(({ incidents, stats }) => {
      const filteredIncidents = filterIncidents(
        incidents,
        this.selectedStatus(),
        this.selectedSeverity(),
      )

      return {
        incidents,
        filteredIncidents,
        stats,
      }
    }),
  )

  onStatusChange(status: StatusFilter): void {
    this.selectedStatus.set(status)
  }

  onSeverityChange(severity: SeverityFilter): void {
    this.selectedSeverity.set(severity)
  }

  /**
   * Statistic cards act as shortcuts for dashboard filters.
   * Selecting one filter dimension resets the other dimension to keep the result explicit.
   */
  onStatClick(filter: StatFilter): void {
    if (filter.type === 'ALL') {
      this.selectedStatus.set('ALL')
      this.selectedSeverity.set('ALL')
      return
    }

    if (filter.type === 'STATUS') {
      this.selectedStatus.set(filter.value)
      this.selectedSeverity.set('ALL')
      return
    }

    this.selectedSeverity.set(filter.value)
    this.selectedStatus.set('ALL')
  }
}
@if (vm$ | async; as vm) {
  <main class="dashboard-page">
    <header class="dashboard-header">
      <h1>War Room Incident Dashboard</h1>
      <p>Diagnose, investigate and resolve technical incidents with Angular.</p>
    </header>

    <app-incident-stats [stats]="vm.stats" (statClick)="onStatClick($event)" />

    <app-incident-filters
      [selectedStatus]="selectedStatus()"
      [selectedSeverity]="selectedSeverity()"
      (statusChange)="onStatusChange($event)"
      (severityChange)="onSeverityChange($event)"
    />

    <p class="dashboard-count">
      Showing {{ vm.filteredIncidents.length }} of {{ vm.incidents.length }} incidents.
    </p>

    <app-incident-list [incidents]="vm.filteredIncidents" />
  </main>
} @else {
  <p>Loading incidents...</p>
}
