// frontend/react-rules-practice/src/features/incidents/components/IncidentCard.tsx
import { memo } from 'react';
import { Link } from 'react-router-dom';
import type { Incident  } from '../types/incidentTypes';
import { SeverityBadge } from './badges/SeverityBadge';
import { StatusBadge } from './badges/StatusBadge';
import './IncidentCard.css';

type IncidentCardProps = {
  incident: Incident ;
};

export const IncidentCard = memo(function IncidentCard({ incident }: IncidentCardProps) {
  return (
    <article className="incident-card">
      <div className="incident-card__header">
        <div>
          <h3>{incident.title}</h3>
          <p className="incident-card__id">{incident.id}</p>
        </div>

        <div className="incident-card__badges">
          <SeverityBadge severity={incident.severity} />
          <StatusBadge status={incident.status} />
        </div>
      </div>

      <p className="incident-card__description">{incident.description}</p>

      <div className="incident-card__footer">
        <span>Notes: {incident.notes.length}</span>

        <Link to={`/incidents/${incident.id}`} className="incident-card__link">
          Open incident
        </Link>
      </div>
    </article>
  );
});

// frontend/angular-rules-practice/src/app/features/incidents/ui/incident-card/incident-card.component.ts
import { Component, input } from '@angular/core'
import { RouterLink } from '@angular/router'
import type { Incident } from '../../models/incident.model'
import { SeverityBadgeComponent } from '../severity-badge/severity-badge.component'
import { StatusBadgeComponent } from '../status-badge/status-badge.component'

@Component({
  selector: 'app-incident-card',
  imports: [RouterLink, StatusBadgeComponent, SeverityBadgeComponent],
  templateUrl: './incident-card.component.html',
  styleUrl: './incident-card.component.css',
})
export class IncidentCardComponent {
  readonly incident = input.required<Incident>()
}
<article class="incident-card">
  <div class="incident-card__header">
    <div>
      <h2>{{ incident().title }}</h2>
      <p class="incident-card__id">{{ incident().id }}</p>
    </div>

    <div class="incident-card__badges">
      <app-status-badge [status]="incident().status" />
      <app-severity-badge [severity]="incident().severity" />
    </div>
  </div>

  <p class="incident-card__description">
    {{ incident().description }}
  </p>

  <div class="incident-card__footer">
    <span>Notes: {{ incident().notes.length }}</span>

    <a [routerLink]="['/incidents', incident().id]" class="incident-card__link">
      Open incident
    </a>
  </div>
</article>
