// frontend/react-rules-practice/src/features/incidents/pages/IncidentDetailsPage.tsx
import { useCallback, useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { Link, useParams } from 'react-router-dom'
import {
  addIncidentNote,
  findIncidentById,
  resolveIncident,
  startInvestigation,
} from '../api/incidentApi'
import type { Incident } from '../types/incidentTypes'
import { Loading } from '../../../shared/components/Loading'
import { SeverityBadge } from '../components/badges/SeverityBadge'
import { StatusBadge } from '../components/badges/StatusBadge'
import './IncidentDetailsPage.css'

export function IncidentDetailsPage() {
  const { id } = useParams<{ id: string }>()

  const [incident, setIncident] = useState<Incident | null>(null)
  const [loading, setLoading] = useState(true)
  const [actionLoading, setActionLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [notification, setNotification] = useState<string | null>(null)

  const loadIncident = useCallback(async () => {
    if (!id) {
      setError('Missing incident id')
      setLoading(false)
      return
    }

    try {
      setLoading(true)
      setError(null)

      const response = await findIncidentById(id)
      setIncident(response)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Unknown error')
    } finally {
      setLoading(false)
    }
  }, [id])

  useEffect(() => {
    void loadIncident()
  }, [loadIncident])

  const handleStartInvestigation = useCallback(async () => {
    if (!incident) return

    try {
      setActionLoading(true)
      setNotification(null)

      const updatedIncident = await startInvestigation(incident.id)
      setIncident(updatedIncident)
      setNotification('Investigation started successfully.')
    } catch (err) {
      setNotification(err instanceof Error ? err.message : 'Unable to start investigation.')
    } finally {
      setActionLoading(false)
    }
  }, [incident])

  const handleAddNote = useCallback(
    async (event: FormEvent<HTMLFormElement>) => {
      event.preventDefault()

      if (!incident) return

      const formData = new FormData(event.currentTarget)
      const author = String(formData.get('author') ?? '').trim()
      const message = String(formData.get('message') ?? '').trim()

      if (!author || !message) {
        setNotification('Author and message are required.')
        return
      }

      try {
        setActionLoading(true)
        setNotification(null)

        const updatedIncident = await addIncidentNote(incident.id, { author, message })
        setIncident(updatedIncident)
        setNotification('Investigation note added successfully.')
        event.currentTarget.reset()
      } catch (err) {
        setNotification(err instanceof Error ? err.message : 'Unable to add note.')
      } finally {
        setActionLoading(false)
      }
    },
    [incident],
  )

  const handleResolve = useCallback(
    async (event: FormEvent<HTMLFormElement>) => {
      event.preventDefault()

      if (!incident) return

      const formData = new FormData(event.currentTarget)
      const rootCause = String(formData.get('rootCause') ?? '').trim()
      const resolution = String(formData.get('resolution') ?? '').trim()

      if (!rootCause || !resolution) {
        setNotification('Root cause and resolution are required.')
        return
      }

      try {
        setActionLoading(true)
        setNotification(null)

        const updatedIncident = await resolveIncident(incident.id, { rootCause, resolution })
        setIncident(updatedIncident)
        setNotification('Incident resolved successfully.')
        event.currentTarget.reset()
      } catch (err) {
        setNotification(err instanceof Error ? err.message : 'Unable to resolve incident.')
      } finally {
        setActionLoading(false)
      }
    },
    [incident],
  )

  if (loading) {
    return <Loading />
  }

  if (error) {
    return (
      <main className="incident-details-page">
        <Link to="/incidents" className="back-link">
          ← Back to dashboard
        </Link>

        <section className="details-error" role="alert">
          <p className="section-eyebrow">Loading error</p>
          <h1>Unable to load incident</h1>
          <p>{error}</p>
          <button type="button" onClick={() => void loadIncident()}>
            Retry
          </button>
        </section>
      </main>
    )
  }

  if (!incident) {
    return null
  }

  const canStartInvestigation = incident.status === 'OPEN'
  const canResolve = incident.status !== 'RESOLVED'

  return (
    <main className="incident-details-page">
      <Link to="/incidents" className="back-link">
        ← Back to dashboard
      </Link>

      <section className="details-hero">
        <div className="details-hero__content">
          <p className="section-eyebrow">Incident details</p>
          <h1>{incident.title}</h1>
          <p className="details-description">{incident.description}</p>

          <dl className="incident-meta-grid">
            <div>
              <dt>Incident ID</dt>
              <dd>{incident.id}</dd>
            </div>
            <div>
              <dt>Created at</dt>
              <dd>{incident.createdAt}</dd>
            </div>
            <div>
              <dt>Resolved at</dt>
              <dd>{incident.resolvedAt ?? 'Not resolved yet'}</dd>
            </div>
          </dl>
        </div>

        <div className="details-hero__side">
          <StatusBadge status={incident.status} />
          <SeverityBadge severity={incident.severity} />
        </div>
      </section>

      <section className="details-section">
        <div className="details-section__header">
          <div>
            <p className="section-eyebrow">Signals</p>
            <h2>Symptoms</h2>
          </div>
          <span className="section-counter">{incident.symptoms.length}</span>
        </div>

        <ul className="symptoms-list">
          {incident.symptoms.map((symptom) => (
            <li key={symptom}>{symptom}</li>
          ))}
        </ul>
      </section>

      <section className="details-section">
        <div className="details-section__header">
          <div>
            <p className="section-eyebrow">Workflow</p>
            <h2>Actions</h2>
          </div>
        </div>

        <div className="action-panel">
          <div>
            <h3>Start investigation</h3>
            <p>
              Move the incident from open state to investigation state so the team can begin
              diagnosis.
            </p>
          </div>

          <button
            type="button"
            disabled={!canStartInvestigation || actionLoading}
            onClick={() => void handleStartInvestigation()}
          >
            Start investigation
          </button>
        </div>
      </section>

      <section className="details-section">
        <div className="details-section__header">
          <div>
            <p className="section-eyebrow">Collaboration</p>
            <h2>Investigation notes</h2>
          </div>
          <span className="section-counter">{incident.notes.length}</span>
        </div>

        {incident.notes.length === 0 ? (
          <p className="empty-state">No notes yet.</p>
        ) : (
          <ul className="notes-list">
            {incident.notes.map((note) => (
              <li key={`${note.author}-${note.createdAt}`}>
                <div className="note-header">
                  <strong>{note.author}</strong>
                  <small>{note.createdAt}</small>
                </div>
                <p>{note.message}</p>
              </li>
            ))}
          </ul>
        )}

        <form className="details-form" onSubmit={(event) => void handleAddNote(event)}>
          <label htmlFor="note-author">Author</label>
          <input id="note-author" name="author" defaultValue="Karim" />

          <label htmlFor="note-message">Message</label>
          <textarea
            id="note-message"
            name="message"
            rows={3}
            placeholder="Describe the investigation step, hypothesis, or finding..."
          />

          <button type="submit" disabled={actionLoading}>
            Add note
          </button>
        </form>
      </section>

      <section className="details-section">
        <div className="details-section__header">
          <div>
            <p className="section-eyebrow">Closure</p>
            <h2>Resolution</h2>
          </div>
        </div>

        {incident.status === 'RESOLVED' ? (
          <div className="resolution-summary">
            <div>
              <h3>Root cause</h3>
              <p>{incident.rootCause}</p>
            </div>

            <div>
              <h3>Resolution</h3>
              <p>{incident.resolution}</p>
            </div>

            <div>
              <h3>Resolved at</h3>
              <p>{incident.resolvedAt}</p>
            </div>
          </div>
        ) : (
          <form className="details-form" onSubmit={(event) => void handleResolve(event)}>
            <label htmlFor="root-cause">Root cause</label>
            <textarea
              id="root-cause"
              name="rootCause"
              rows={3}
              placeholder="Explain the technical cause of the incident..."
            />

            <label htmlFor="resolution">Resolution</label>
            <textarea
              id="resolution"
              name="resolution"
              rows={3}
              placeholder="Explain what was done to resolve the incident..."
            />

            <button type="submit" disabled={!canResolve || actionLoading}>
              Resolve incident
            </button>
          </form>
        )}
      </section>

      <p className="details-notification" aria-live="polite">
        {notification}
      </p>
    </main>
  )
}

// frontend/angular-rules-practice/src/app/features/incidents/pages/incident-details-page/incident-details-page.component.ts
import { AsyncPipe } from '@angular/common'
import { Component, inject, signal } from '@angular/core'
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms'
import { ActivatedRoute, RouterLink } from '@angular/router'
import { catchError, EMPTY, switchMap, tap } from 'rxjs'
import { IncidentService } from '../../data-access/incident.service'
import type { Incident } from '../../models/incident.model'
import { SeverityBadgeComponent } from '../../ui/severity-badge/severity-badge.component'
import { StatusBadgeComponent } from '../../ui/status-badge/status-badge.component'

@Component({
  selector: 'app-incident-details-page',
  imports: [
    AsyncPipe,
    RouterLink,
    ReactiveFormsModule,
    StatusBadgeComponent,
    SeverityBadgeComponent,
  ],
  templateUrl: './incident-details-page.component.html',
  styleUrl: './incident-details-page.component.css',
})
export class IncidentDetailsPageComponent {
  private readonly route = inject(ActivatedRoute)
  private readonly incidentService = inject(IncidentService)
  private readonly formBuilder = inject(FormBuilder)

  readonly incident = signal<Incident | null>(null)
  readonly loading = signal<boolean>(true)
  readonly actionLoading = signal<boolean>(false)
  readonly error = signal<string | null>(null)
  readonly notification = signal<string | null>(null)

  readonly noteForm = this.formBuilder.nonNullable.group({
    author: ['Karim', Validators.required],
    message: ['', Validators.required],
  })

  readonly resolveForm = this.formBuilder.nonNullable.group({
    rootCause: ['', Validators.required],
    resolution: ['', Validators.required],
  })

  readonly incident$ = this.route.paramMap.pipe(
    tap(() => {
      this.loading.set(true)
      this.error.set(null)
    }),
    switchMap((params) => {
      const id = params.get('id')

      if (!id) {
        this.loading.set(false)
        this.error.set('Missing incident id')
        return EMPTY
      }

      return this.incidentService.findById(id).pipe(
        tap((incident) => {
          this.incident.set(incident)
          this.loading.set(false)
        }),
        catchError((err: unknown) => {
          this.error.set(err instanceof Error ? err.message : 'Unable to load incident.')
          this.loading.set(false)
          return EMPTY
        }),
      )
    }),
  )

  get canStartInvestigation(): boolean {
    return this.incident()?.status === 'OPEN'
  }

  get canResolve(): boolean {
    return this.incident()?.status !== 'RESOLVED'
  }

  startInvestigation(): void {
    const incident = this.incident()

    if (!incident) {
      return
    }

    this.actionLoading.set(true)
    this.notification.set(null)

    this.incidentService.startInvestigation(incident.id).subscribe({
      next: (updatedIncident) => {
        this.incident.set(updatedIncident)
        this.notification.set('Investigation started successfully.')
        this.actionLoading.set(false)
      },
      error: (err: unknown) => {
        this.notification.set(err instanceof Error ? err.message : 'Unable to start investigation.')
        this.actionLoading.set(false)
      },
    })
  }

  addNote(): void {
    const incident = this.incident()

    if (!incident || this.noteForm.invalid) {
      this.noteForm.markAllAsTouched()
      this.notification.set('Author and message are required.')
      return
    }

    this.actionLoading.set(true)
    this.notification.set(null)

    this.incidentService.addNote(incident.id, this.noteForm.getRawValue()).subscribe({
      next: (updatedIncident) => {
        this.incident.set(updatedIncident)
        this.noteForm.reset({
          author: 'Karim',
          message: '',
        })
        this.notification.set('Investigation note added successfully.')
        this.actionLoading.set(false)
      },
      error: (err: unknown) => {
        this.notification.set(err instanceof Error ? err.message : 'Unable to add note.')
        this.actionLoading.set(false)
      },
    })
  }

  resolveIncident(): void {
    const incident = this.incident()

    if (!incident || this.resolveForm.invalid) {
      this.resolveForm.markAllAsTouched()
      this.notification.set('Root cause and resolution are required.')
      return
    }

    this.actionLoading.set(true)
    this.notification.set(null)

    this.incidentService.resolve(incident.id, this.resolveForm.getRawValue()).subscribe({
      next: (updatedIncident) => {
        this.incident.set(updatedIncident)
        this.resolveForm.reset()
        this.notification.set('Incident resolved successfully.')
        this.actionLoading.set(false)
      },
      error: (err: unknown) => {
        this.notification.set(err instanceof Error ? err.message : 'Unable to resolve incident.')
        this.actionLoading.set(false)
      },
    })
  }
}
@if (incident$ | async) {}

@if (loading()) {
  <p>Loading incident...</p>
} @else if (error()) {
  <main class="incident-details-page">
    <a routerLink="/incidents" class="back-link">← Back to dashboard</a>

    <section class="details-error" role="alert">
      <p class="section-eyebrow">Loading error</p>
      <h1>Unable to load incident</h1>
      <p>{{ error() }}</p>
    </section>
  </main>
} @else if (incident(); as selectedIncident) {
  <main class="incident-details-page">
    <a routerLink="/incidents" class="back-link">← Back to dashboard</a>

    <section class="details-hero">
      <div class="details-hero__content">
        <p class="section-eyebrow">Incident details</p>
        <h1>{{ selectedIncident.title }}</h1>
        <p class="details-description">{{ selectedIncident.description }}</p>

        <dl class="incident-meta-grid">
          <div>
            <dt>Incident ID</dt>
            <dd>{{ selectedIncident.id }}</dd>
          </div>

          <div>
            <dt>Created at</dt>
            <dd>{{ selectedIncident.createdAt }}</dd>
          </div>

          <div>
            <dt>Resolved at</dt>
            <dd>{{ selectedIncident.resolvedAt ?? 'Not resolved yet' }}</dd>
          </div>
        </dl>
      </div>

      <div class="details-hero__side">
        <app-status-badge [status]="selectedIncident.status" />
        <app-severity-badge [severity]="selectedIncident.severity" />
      </div>
    </section>

    <section class="details-section">
      <div class="details-section__header">
        <div>
          <p class="section-eyebrow">Signals</p>
          <h2>Symptoms</h2>
        </div>

        <span class="section-counter">{{ selectedIncident.symptoms.length }}</span>
      </div>

      <ul class="symptoms-list">
        @for (symptom of selectedIncident.symptoms; track symptom) {
          <li>{{ symptom }}</li>
        }
      </ul>
    </section>

    <section class="details-section">
      <div class="details-section__header">
        <div>
          <p class="section-eyebrow">Workflow</p>
          <h2>Actions</h2>
        </div>
      </div>

      <div class="action-panel">
        <div>
          <h3>Start investigation</h3>
          <p>
            Move the incident from open state to investigation state so the team can begin
            diagnosis.
          </p>
        </div>

        <button
          type="button"
          [disabled]="!canStartInvestigation || actionLoading()"
          (click)="startInvestigation()"
        >
          Start investigation
        </button>
      </div>
    </section>

    <section class="details-section">
      <div class="details-section__header">
        <div>
          <p class="section-eyebrow">Collaboration</p>
          <h2>Investigation notes</h2>
        </div>

        <span class="section-counter">{{ selectedIncident.notes.length }}</span>
      </div>

      @if (selectedIncident.notes.length === 0) {
        <p class="empty-state">No notes yet.</p>
      } @else {
        <ul class="notes-list">
          @for (note of selectedIncident.notes; track note.author + note.createdAt) {
            <li>
              <div class="note-header">
                <strong>{{ note.author }}</strong>
                <small>{{ note.createdAt }}</small>
              </div>
              <p>{{ note.message }}</p>
            </li>
          }
        </ul>
      }

      <form class="details-form" [formGroup]="noteForm" (ngSubmit)="addNote()">
        <label for="note-author">Author</label>
        <input id="note-author" formControlName="author" />

        <label for="note-message">Message</label>
        <textarea
          id="note-message"
          formControlName="message"
          rows="3"
          placeholder="Describe the investigation step, hypothesis, or finding..."
        ></textarea>

        <button type="submit" [disabled]="actionLoading()">Add note</button>
      </form>
    </section>

    <section class="details-section">
      <div class="details-section__header">
        <div>
          <p class="section-eyebrow">Closure</p>
          <h2>Resolution</h2>
        </div>
      </div>

      @if (selectedIncident.status === 'RESOLVED') {
        <div class="resolution-summary">
          <div>
            <h3>Root cause</h3>
            <p>{{ selectedIncident.rootCause }}</p>
          </div>

          <div>
            <h3>Resolution</h3>
            <p>{{ selectedIncident.resolution }}</p>
          </div>

          <div>
            <h3>Resolved at</h3>
            <p>{{ selectedIncident.resolvedAt }}</p>
          </div>
        </div>
      } @else {
        <form class="details-form" [formGroup]="resolveForm" (ngSubmit)="resolveIncident()">
          <label for="root-cause">Root cause</label>
          <textarea
            id="root-cause"
            formControlName="rootCause"
            rows="3"
            placeholder="Explain the technical cause of the incident..."
          ></textarea>

          <label for="resolution">Resolution</label>
          <textarea
            id="resolution"
            formControlName="resolution"
            rows="3"
            placeholder="Explain what was done to resolve the incident..."
          ></textarea>

          <button type="submit" [disabled]="!canResolve || actionLoading()">
            Resolve incident
          </button>
        </form>
      }
    </section>

    <p class="details-notification" aria-live="polite">
      {{ notification() }}
    </p>
  </main>
}
