// frontend/react-rules-practice/src/features/incidents/components/IncidentFilters.tsx
import './IncidentFilters.css'
import type { IncidentSeverity, IncidentStatus } from '../types/incidentTypes'

export type StatusFilter = 'ALL' | IncidentStatus
export type SeverityFilter = 'ALL' | IncidentSeverity

type IncidentFiltersProps = {
  selectedStatus: StatusFilter
  selectedSeverity: SeverityFilter
  onStatusChange: (status: StatusFilter) => void
  onSeverityChange: (severity: SeverityFilter) => void
}

export function IncidentFilters({
  selectedStatus,
  selectedSeverity,
  onStatusChange,
  onSeverityChange,
}: IncidentFiltersProps) {
  return (
    <section className="incident-filters" aria-label="Incident filters">
      <div className="incident-filter-field">
        <label htmlFor="status-filter">Status</label>
        <select
          id="status-filter"
          value={selectedStatus}
          onChange={(event) => onStatusChange(event.target.value as StatusFilter)}
        >
          <option value="ALL">All</option>
          <option value="OPEN">Open</option>
          <option value="INVESTIGATING">Investigating</option>
          <option value="RESOLVED">Resolved</option>
        </select>
      </div>

      <div className="incident-filter-field">
        <label htmlFor="severity-filter">Severity</label>
        <select
          id="severity-filter"
          value={selectedSeverity}
          onChange={(event) => onSeverityChange(event.target.value as SeverityFilter)}
        >
          <option value="ALL">All</option>
          <option value="LOW">Low</option>
          <option value="MEDIUM">Medium</option>
          <option value="HIGH">High</option>
          <option value="CRITICAL">Critical</option>
        </select>
      </div>
    </section>
  )
}

// frontend/angular-rules-practice/src/app/features/incidents/ui/incident-filters/incident-filters.component.ts
import { Component, input, output } from '@angular/core'
import type { SeverityFilter, StatusFilter } from '../../models/incident-filter.model'

@Component({
  selector: 'app-incident-filters',
  templateUrl: './incident-filters.component.html',
  styleUrl: './incident-filters.component.css',
})
export class IncidentFiltersComponent {
  readonly selectedStatus = input.required<StatusFilter>()
  readonly selectedSeverity = input.required<SeverityFilter>()

  readonly statusChange = output<StatusFilter>()
  readonly severityChange = output<SeverityFilter>()

  onStatusChange(value: string): void {
    this.statusChange.emit(value as StatusFilter)
  }

  onSeverityChange(value: string): void {
    this.severityChange.emit(value as SeverityFilter)
  }
}
<section class="incident-filters" aria-label="Incident filters">
  <div class="incident-filter-field">
    <label for="status-filter">Status</label>
    <select
      id="status-filter"
      [value]="selectedStatus()"
      (change)="onStatusChange($any($event.target).value)"
    >
      <option value="ALL">All</option>
      <option value="OPEN">Open</option>
      <option value="INVESTIGATING">Investigating</option>
      <option value="RESOLVED">Resolved</option>
    </select>
  </div>

  <div class="incident-filter-field">
    <label for="severity-filter">Severity</label>
    <select
      id="severity-filter"
      [value]="selectedSeverity()"
      (change)="onSeverityChange($any($event.target).value)"
    >
      <option value="ALL">All</option>
      <option value="LOW">Low</option>
      <option value="MEDIUM">Medium</option>
      <option value="HIGH">High</option>
      <option value="CRITICAL">Critical</option>
    </select>
  </div>
</section>
