// frontend/react-rules-practice/src/features/incidents/components/badges/StatusBadge.tsx
import type { IncidentStatus } from '../../types/incidentTypes';
import './Badge.css';

type StatusBadgeProps = {
  status: IncidentStatus;
};

const STATUS_LABELS: Record<IncidentStatus, string> = {
  OPEN: 'Open',
  INVESTIGATING: 'Investigating',
  RESOLVED: 'Resolved',
};

export function StatusBadge({ status }: StatusBadgeProps) {
  return (
    <span className={`badge badge--status badge--status-${status.toLowerCase()}`}>
      {STATUS_LABELS[status]}
    </span>
  );
}

// frontend/angular-rules-practice/src/app/features/incidents/ui/status-badge/status-badge.component.ts
import { Component, input } from '@angular/core'
import type { IncidentStatus } from '../../models/incident.model'

@Component({
  selector: 'app-status-badge',
  templateUrl: './status-badge.component.html',
  styleUrl: './status-badge.component.css',
})
export class StatusBadgeComponent {
  readonly status = input.required<IncidentStatus>()

  readonly labels: Record<IncidentStatus, string> = {
    OPEN: 'Open',
    INVESTIGATING: 'Investigating',
    RESOLVED: 'Resolved',
  }

  get cssClass(): string {
    return `badge badge--status-${this.status().toLowerCase()}`
  }

  get label(): string {
    return this.labels[this.status()]
  }
}
