// frontend/angular-rules-practice/src/app/features/incidents/ui/severity-badge/severity-badge.component.ts
import { Component, input } from '@angular/core'
import type { IncidentSeverity } from '../../models/incident.model'

@Component({
  selector: 'app-severity-badge',
  templateUrl: './severity-badge.component.html',
  styleUrl: './severity-badge.component.css',
})
export class SeverityBadgeComponent {
  readonly severity = input.required<IncidentSeverity>()

  readonly labels: Record<IncidentSeverity, string> = {
    LOW: 'Low',
    MEDIUM: 'Medium',
    HIGH: 'High',
    CRITICAL: 'Critical',
  }

  get cssClass(): string {
    return `badge badge--severity-${this.severity().toLowerCase()}`
  }

  get label(): string {
    return this.labels[this.severity()]
  }
}

// frontend/react-rules-practice/src/features/incidents/components/badges/SeverityBadge.tsx
import type { IncidentSeverity } from '../../types/incidentTypes';
import './Badge.css';

type SeverityBadgeProps = {
  severity: IncidentSeverity;
};

const SEVERITY_LABELS: Record<IncidentSeverity, string> = {
  LOW: 'Low',
  MEDIUM: 'Medium',
  HIGH: 'High',
  CRITICAL: 'Critical',
};

export function SeverityBadge({ severity }: SeverityBadgeProps) {
  return (
    <span className={`badge badge--severity badge--severity-${severity.toLowerCase()}`}>
      {SEVERITY_LABELS[severity]}
    </span>
  );
}
