// frontend/react-rules-practice/src/features/incidents/components/IncidentStats.tsx
import './IncidentStats.css'
import type {
  IncidentSeverity,
  IncidentStats as IncidentStatsType,
  IncidentStatus,
} from '../types/incidentTypes'

type StatFilter =
  | { type: 'ALL' }
  | { type: 'STATUS'; value: IncidentStatus }
  | { type: 'SEVERITY'; value: IncidentSeverity }

type IncidentStatsProps = {
  stats: IncidentStatsType | null
  onStatClick: (filter: StatFilter) => void
}

type StatItem = {
  label: string
  value: number
  filter: StatFilter
}

export function IncidentStats({ stats, onStatClick }: IncidentStatsProps) {
  if (!stats) {
    return null
  }

  const items: StatItem[] = [
    { label: 'Total', value: stats.total, filter: { type: 'ALL' } },
    { label: 'Open', value: stats.open, filter: { type: 'STATUS', value: 'OPEN' } },
    {
      label: 'Investigating',
      value: stats.investigating,
      filter: { type: 'STATUS', value: 'INVESTIGATING' },
    },
    { label: 'Resolved', value: stats.resolved, filter: { type: 'STATUS', value: 'RESOLVED' } },
    { label: 'Critical', value: stats.critical, filter: { type: 'SEVERITY', value: 'CRITICAL' } },
    { label: 'High', value: stats.high, filter: { type: 'SEVERITY', value: 'HIGH' } },
    { label: 'Medium', value: stats.medium, filter: { type: 'SEVERITY', value: 'MEDIUM' } },
    { label: 'Low', value: stats.low, filter: { type: 'SEVERITY', value: 'LOW' } },
  ]

  return (
    <section className="incident-stats" aria-label="Incident statistics">
      {items.map((item) => (
        <button
          type="button"
          className="incident-stat-card"
          key={item.label}
          onClick={() => onStatClick(item.filter)}
        >
          <span className="incident-stat-label">{item.label}</span>
          <span className="incident-stat-value">{item.value}</span>
        </button>
      ))}
    </section>
  )
}

// frontend/angular-rules-practice/src/app/features/incidents/ui/incident-stats/incident-stats.component.ts
import { Component, input, output } from '@angular/core'
import type { IncidentStats } from '../../models/incident.model'
import type { StatFilter } from '../../models/incident-filter.model'

type StatItem = {
  label: string
  value: number
  filter: StatFilter
}

@Component({
  selector: 'app-incident-stats',
  templateUrl: './incident-stats.component.html',
  styleUrl: './incident-stats.component.css',
})
export class IncidentStatsComponent {
  readonly stats = input.required<IncidentStats>()
  readonly statClick = output<StatFilter>()

  get items(): StatItem[] {
    const stats = this.stats()

    return [
      { label: 'Total', value: stats.total, filter: { type: 'ALL' } },
      { label: 'Open', value: stats.open, filter: { type: 'STATUS', value: 'OPEN' } },
      {
        label: 'Investigating',
        value: stats.investigating,
        filter: { type: 'STATUS', value: 'INVESTIGATING' },
      },
      { label: 'Resolved', value: stats.resolved, filter: { type: 'STATUS', value: 'RESOLVED' } },
      { label: 'Critical', value: stats.critical, filter: { type: 'SEVERITY', value: 'CRITICAL' } },
      { label: 'High', value: stats.high, filter: { type: 'SEVERITY', value: 'HIGH' } },
      { label: 'Medium', value: stats.medium, filter: { type: 'SEVERITY', value: 'MEDIUM' } },
      { label: 'Low', value: stats.low, filter: { type: 'SEVERITY', value: 'LOW' } },
    ]
  }

  onStatClick(filter: StatFilter): void {
    this.statClick.emit(filter)
  }
}
<section class="incident-stats" aria-label="Incident statistics">
  @for (item of items; track item.label) {
    <button type="button" class="incident-stat-card" (click)="onStatClick(item.filter)">
      <span class="incident-stat-label">{{ item.label }}</span>
      <span class="incident-stat-value">{{ item.value }}</span>
    </button>
  }
</section>
